import {
  StudentProfile,
  SprintData,
  LearningOutcome,
  StoryItem,
  ProjectSolution,
  AIToolItem,
  FeedbackReflectionItem,
  EvidenceLink,
  WorkItem,
} from './portfolioTypes';

export const STUDENT_PROFILE: StudentProfile = {
  name: 'Justin Man',
  title: 'Student Minor Futureproof met AI',
  institution: 'Hogeschool',
  program: 'Informatica / Software Development',
  minor: 'Minor Futureproof met AI',
  academicYear: '2026 - 2027',
  bio: 'Welkom op mijn persoonlijke portfolio website! Hier verzamel ik alle bewijzen, verhalen, prototypes en reflecties van de 8 sprints binnen de minor Futureproof met AI.',
  email: 'justinman@outlook.com',
  githubUrl: 'https://github.com',
  linkedinUrl: 'https://linkedin.com',
  location: 'Nederland',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
  personalStory: {
    whoAmI: 'Mijn naam is Justin Man. Als nieuwsgierige student ben ik gefascineerd door de snelle opkomst van kunstmatige intelligentie en hoe technologie ons dagelijks leven eenvoudiger en creatiever kan maken.',
    passionsAndJoy: 'Ik word oprecht blij van het bedenken en bouwen van slimme, werkende tools die écht nut hebben voor mensen. Daarnaast geniet ik van creatief bezig zijn met AI, programmeren, nieuwe concepten uitproberen, sporten en sparren met teamgenoten.',
    whyThisMinor: 'Ik heb gekozen voor Futureproof met AI om niet alleen theorie te leren, maar direct met de nieuwste AI-tools (zoals Google AI Studio en moderne LLM-agents) tastbare oplossingen en prototypes neer te zetten.',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    funFacts: [
      'Gepassioneerd door Human-Centered AI en handige web-apps',
      'Bouwt graag praktische prototypes met Google AI Studio & React',
      'Blij met een goede kop koffie en een helder geschreven prompt',
      'Doel: tastbare bewijzen leveren voor alle 5 de minor leeruitkomsten'
    ],
  },
  learningGoals: [
    {
      id: 'lg-1',
      title: 'Geavanceerde AI-integratie met Gemini API & Agents',
      description: 'Zelfstandig full-stack applicaties bouwen met server-side LLM-aanroepen, streaming antwoorden en gestructureerde JSON-outputs met actuele SDK\'s.',
      targetSprint: 'Sprint 1 - 3',
      category: 'Technisch',
    },
    {
      id: 'lg-2',
      title: 'Human-Centered AI Interaction & UI/UX Design',
      description: 'Interfaces ontwerpen waarbij AI transparant, behulpzaam en frictieloos aanvoelt, zonder cognitieve overbelasting of dark patterns.',
      targetSprint: 'Sprint 2 - 5',
      category: 'Design & UX',
    },
    {
      id: 'lg-3',
      title: 'Ethisch toetsen & Data-privacy waarborgen in AI',
      description: 'Kritisch evalueren van AI-outputs op vooringenomenheid (bias), data-soevereiniteit en privacy conform AVG bij opslag en verwerking.',
      targetSprint: 'Sprint 4 - 8',
      category: 'Ethiek & Impact',
    },
    {
      id: 'lg-4',
      title: 'Agile & Story-Driven Iteratiecyclus',
      description: 'Elke sprint strak structureren met Research Stories, User Stories en Learning Stories, ondersteund door tastbare bewijzen en reflecties.',
      targetSprint: 'Sprint 1 - 8',
      category: 'Methodologie',
    },
  ],
};

export const INITIAL_WORK_ITEMS: WorkItem[] = [
  {
    id: 'work-1',
    title: 'Werkend Digitaal Dagboek Prototype (Sprint 2)',
    sprintNumber: 2,
    type: 'Werkend Prototype',
    whatMade: 'Een interactieve, mensgerichte webapplicatie met een 4-vragen reflectiemethode, automatische stemmingstracking, Gemini-aangedreven dagelijkse inspiratiespreuken, PIN-code beveiliging en Excel data-export (.xlsx).',
    howMadeOrTech: 'Google AI Studio, React 19, TypeScript, Gemini 3.8 Flash, SheetJS, Express proxy',
    learningOutcomeCodes: ['LU-1', 'LU-2', 'LU-3', 'LU-4'],
    learningOutcomeCode: 'LU-2',
    description: 'Interactieve applicatie met 4 dagelijkse reflectievragen, AI-spreuk generator via Gemini API en Excel-export.',
    url: '#projects',
    githubUrl: 'https://github.com',
    status: 'Opgeleverd',
    dateAdded: '2026-09-08',
  },
  {
    id: 'work-2',
    title: 'Portfolio Website in Google AI Studio (Sprint 1)',
    sprintNumber: 1,
    type: 'Werkend Prototype',
    whatMade: 'Een centrale portfolio webapplicatie (Opdracht 1 & 2) waarin al mijn werkstukken, bewijzen per sprint, persoonlijke verhaal en koppelingen aan de 5 leeruitkomsten interactief beheerd en getoond worden.',
    howMadeOrTech: 'Google AI Studio, Vite, React, Tailwind CSS, LocalStorage state persistence',
    learningOutcomeCodes: ['LU-1', 'LU-2', 'LU-5'],
    learningOutcomeCode: 'LU-1',
    description: 'Opdracht 1: centrale portfolio website waarin alle bewijzen, sprints en leeruitkomsten worden vastgelegd.',
    url: 'https://ais-pre-kicwhcuqnw6anl342wcpjj-595862977345.europe-west1.run.app',
    githubUrl: 'https://github.com',
    status: 'Opgeleverd',
    dateAdded: '2026-09-08',
  },
  {
    id: 'work-3',
    title: 'Prompt Engineering Experimenteer-Suite & Onderzoek',
    sprintNumber: 1,
    type: 'Onderzoeksverslag',
    whatMade: 'Vergelijkend onderzoek en testsuite voor LLM-prompts: systematisch getoetst op system instructions, few-shot voorbeelden, JSON-schema afdwinging en temperatuurinstellingen om hallucinaties tegen te gaan.',
    howMadeOrTech: 'Google AI Studio, Gemini 3.1 & 3.8 Flash, Structured Outputs, JSON Schema',
    learningOutcomeCodes: ['LU-1', 'LU-4'],
    learningOutcomeCode: 'LU-4',
    description: 'Vergelijkend onderzoek naar system prompts, temperature instellingen en output consistentie.',
    url: '#stories',
    status: 'Opgeleverd',
    dateAdded: '2026-09-05',
  },
  {
    id: 'work-4',
    title: 'Data-Soevereiniteit: Excel Data-Export Module',
    sprintNumber: 2,
    type: 'Code Repository',
    whatMade: 'Een standalone TypeScript-module die dagboeknotities, gemoedstoestanden en reflectie-antwoorden omzet naar een gestructureerd .xlsx spreadsheet, zodat de gebruiker altijd volledige controle over eigen data behoudt.',
    howMadeOrTech: 'SheetJS (xlsx), TypeScript, Client-side Blob download',
    learningOutcomeCodes: ['LU-3', 'LU-4'],
    learningOutcomeCode: 'LU-3',
    description: 'Volledige export naar .xlsx bestand met één klik voor datasoevereiniteit conform privacy-richtlijnen.',
    url: '#projects',
    githubUrl: 'https://github.com',
    status: 'Opgeleverd',
    dateAdded: '2026-09-07',
  },
  {
    id: 'work-5',
    title: 'Show & Tell Presentatie & Peer Review (Sprint 2)',
    sprintNumber: 2,
    type: 'Show & Tell Presentatie',
    whatMade: 'Presentatieslides en live demonstratie van het Digitaal Dagboek tijdens de peer review sessie van de minor. Inclusief demonstratie van de AI-integratie, feedback van docenten/medestudenten en concrete actiepunten.',
    howMadeOrTech: 'Show & Tell presentatie, Live Demo, Peer review rubric',
    learningOutcomeCodes: ['LU-2', 'LU-5'],
    learningOutcomeCode: 'LU-5',
    description: 'Show & Tell sprintoplevering met live demo van het prototype en verwerking van ontvangen feedback.',
    url: '#feedback',
    status: 'Gepresenteerd',
    dateAdded: '2026-09-08',
  },
  {
    id: 'work-6',
    title: 'Ethische Beoordeling & Privacy Risicoanalyse (AVG & AI)',
    sprintNumber: 2,
    type: 'Onderzoeksverslag',
    whatMade: 'Ethische en juridische impactanalyse van AI in persoonlijke dagboekapps: evaluatie van dataopslag (lokaal vs cloud), risico op emotionele afhankelijkheid van AI-adviezen, en mitigerende maatregelen zoals PIN-beveiliging.',
    howMadeOrTech: 'Responsible AI Framework, EU AI Act richtlijnen, Privacy by Design',
    learningOutcomeCodes: ['LU-3'],
    learningOutcomeCode: 'LU-3',
    description: 'Onderzoek naar ethische kaders, dataopslag en risicomitigatie bij empathische AI-systemen.',
    url: '#stories',
    status: 'Opgeleverd',
    dateAdded: '2026-09-06',
  },
  {
    id: 'work-7',
    title: 'RAG & Vector Embeddings Architectuur Concept',
    sprintNumber: 3,
    type: 'Onderzoeksverslag',
    whatMade: 'Conceptueel architectuurontwerp voor een Retrieval-Augmented Generation (RAG) assistent die lesmateriaal en documenten indexeert met embeddings om betrouwbare antwoorden te genereren met bronvermelding.',
    howMadeOrTech: 'Vector database concepten, Cosine similarity, Chunking strategie (500 tokens)',
    learningOutcomeCodes: ['LU-1', 'LU-4'],
    learningOutcomeCode: 'LU-1',
    description: 'Onderzoek en architectuurschets voor RAG pipelines ter voorbereiding op Sprint 3.',
    url: '#stories',
    status: 'In ontwikkeling',
    dateAdded: '2026-09-08',
  },
];

export const INITIAL_EVIDENCE_LINKS: EvidenceLink[] = INITIAL_WORK_ITEMS;

export const SPRINTS_DATA: SprintData[] = [
  {
    number: 1,
    title: 'Verkenning & Generative AI Kick-off',
    theme: 'AI Fundamenten, Prompt Engineering & Snelle Prototypes',
    period: 'Sprint 1 (Week 1 - 2)',
    summary: 'Kennismaking met het AI-landschap, opzetten van development-pipelines in Google AI Studio en bouwen van eerste werkende LLM-prototypes.',
    focusAreas: ['Prompt Patterns', 'Google AI Studio', 'Vite & React Setup', 'Persoonlijke Leerdoelen'],
    status: 'Afgerond',
  },
  {
    number: 2,
    title: 'Human-AI Interaction & Digitaal Dagboek',
    theme: 'Persoonlijke Assistentie, Empathische Interactie & Lokale Persistentie',
    period: 'Sprint 2 (Week 3 - 4)',
    summary: 'Ontwikkeling van een mensgericht Digitaal Dagboek met gemoedstoestand-analyse, Gemini-gedreven dagelijkse reflecties en PIN-beveiliging.',
    focusAreas: ['Gemini 3.1 & 3.8 Flash', 'Offline State Management', 'Data-export (Excel)', 'Beveiligingsarchitectuur'],
    status: 'Afgerond',
  },
  {
    number: 3,
    title: 'RAG & Externe Data Integratie',
    theme: 'Retrieval Augmented Generation & Kennisbanken',
    period: 'Sprint 3 (Week 5 - 6)',
    summary: 'Onderzoek naar contextverrijking via embeddings, vector search en het ontsluiten van gestructureerde documenten voor feitelijke AI-antwoorden.',
    focusAreas: ['Vector Embeddings', 'Context Ingestion', 'Hallucinatie-reductie', 'Kennisarchitectuur'],
    status: 'In uitvoering',
  },
  {
    number: 4,
    title: 'Autonomous Agents & Multi-Tool Orchestratie',
    theme: 'Agentic Workflows, Function Calling & Automatisering',
    period: 'Sprint 4 (Week 7 - 8)',
    summary: 'Agents ontwerpen die taakgericht acties uitvoeren, beslissingen nemen en externe API’s dynamisch aanroepen met validatielussen.',
    focusAreas: ['Function Calling', 'Antigravity Agent Patterns', 'Multi-step Planning', 'Foutafhandeling'],
    status: 'Gepland',
  },
  {
    number: 5,
    title: 'Ethiek, Explainability & Responsible AI',
    theme: 'Ethische Toetsing, Bias Detectie & Transparantie',
    period: 'Sprint 5 (Week 9 - 10)',
    summary: 'Audit van AI-beslissingsmodellen, uitlegbaarheid voor eindgebruikers en borging van menselijke controle (human-in-the-loop).',
    focusAreas: ['EU AI Act Richtlijnen', 'XAI (Explainable AI)', 'Model Card Audits', 'Human-in-the-loop'],
    status: 'Gepland',
  },
  {
    number: 6,
    title: 'Multimodal AI & Speech/Vision Interfaces',
    theme: 'Visuele analyse, Audio & Realtime Conversatie',
    period: 'Sprint 6 (Week 11 - 12)',
    summary: 'Integratie van beeldverwerking en steminteractie via multimodale modellen voor toegankelijkere en rijkere gebruikerservaringen.',
    focusAreas: ['Gemini Vision API', 'Audio input/output', 'Accessibility (a11y)', 'Edge cases'],
    status: 'Gepland',
  },
  {
    number: 7,
    title: 'Domeinspecifieke Praktijkoplossing (Minor Project)',
    theme: 'Grootschalig Praktijkprototype voor Opdrachtgever',
    period: 'Sprint 7 (Week 13 - 16)',
    summary: 'Samen met een maatschappelijke of zakelijke partner een schaalbare AI-applicatie ontwikkelen die een reëel knelpunt wegneemt.',
    focusAreas: ['Ketenintegratie', 'Gebruikerstesten', 'Performance & Caching', 'Cloud Run Deployment'],
    status: 'Gepland',
  },
  {
    number: 8,
    title: 'Eindassessment, Portfolio & Future Vision',
    theme: 'Synthese van Leeruitkomsten, Expositie & Verdediging',
    period: 'Sprint 8 (Week 17 - 20)',
    summary: 'Afronding van het portfolio, aantonen van alle 5 de minor leeruitkomsten, einddemonstratie en visie op de toekomst van AI.',
    focusAreas: ['Assessmentverdediging', 'Peer Reviews', 'Open Source Deliverables', 'Reflectiedocument'],
    status: 'Gepland',
  },
];

export const LEARNING_OUTCOMES: LearningOutcome[] = [
  {
    id: 1,
    code: 'LU-1',
    title: 'AI-impact op de toekomstige beroepspraktijk analyseren en evalueren',
    officialDescription: 'Je kunt zelfstandig onderzoek doen naar de impact van AI in jouw toekomstig beroep en vaststellen welke nieuwe AI en digitale vaardigheden daarvoor nodig zijn.',
    status: 'Bewezen',
    progressPercentage: 90,
    linkedEvidenceCount: 5,
    requiredMinPass: 2,
    criteria: [
      'Onderzoekt hoe AI werkprocessen, rollen en competenties in het vakgebied transformeert.',
      'Formuleert gerichte leervragen over nieuwe benodigde AI- en digitale vaardigheden.',
      'Onderbouwt analyses met actuele bronnen, expertinterviews of praktijkcases.',
    ],
  },
  {
    id: 2,
    code: 'LU-2',
    title: 'Praktijkgerichte AI oplossing ontwerpen, realiseren en presenteren',
    officialDescription: 'Je kunt zelfstandig een AI oplossing ontwerpen, realiseren en presenteren die een specifieke beroepspraktijk radicaal transformeert (verandert).',
    status: 'Aangetoond',
    progressPercentage: 85,
    linkedEvidenceCount: 5,
    requiredMinPass: 4,
    criteria: [
      'Ontwerpt en bouwt werkende AI proof-of-concepts (apps, prototypes, vibe-coding applicaties).',
      'Definieert duidelijke acceptatie- en kwaliteitscriteria voor oplevering in sprints.',
      'Presenteert het gerealiseerde product overtuigend tijdens Show & Tell sessies.',
    ],
  },
  {
    id: 3,
    code: 'LU-3',
    title: 'Ethiek en verantwoordelijk AI-gebruik beoordelen',
    officialDescription: 'Je kunt zelfstandig de ethische vraagstukken en uitdagingen van AI in je vakgebied identificeren en aanbevelingen formuleren voor verantwoord AI-gebruik, rekening houdend met privacy, bias en transparantie.',
    status: 'Bewezen',
    progressPercentage: 80,
    linkedEvidenceCount: 4,
    requiredMinPass: 2,
    criteria: [
      'Identificeert risico’s rondom privacy, datasoevereiniteit, hallucinaties en bias.',
      'Formuleert concrete aanbevelingen voor verantwoord en transparant AI-gebruik.',
      'Implementeert maatregelen (bijv. lokale gegevensverwerking, veilige API-sleutels, gebruikerscontrole).',
    ],
  },
  {
    id: 4,
    code: 'LU-4',
    title: 'AI Tools en technieken gebruiken',
    officialDescription: 'Je kunt zelfstandig verschillende AI-tools en platforms toepassen (zoals AI machine learning technieken, chatbots, agents, prompts, etc) en deze gebruiken om specifieke taken binnen je vakgebied op te lossen.',
    status: 'Aangetoond',
    progressPercentage: 85,
    linkedEvidenceCount: 6,
    requiredMinPass: 4,
    criteria: [
      'Past geavanceerde promptingtechnieken, LLM-APIs en Vibe-coding toe.',
      'Bouwt en orchestreert AI-agents en geautomatiseerde workflows (zoals n8n, Make, scripts).',
      'Selecteert doelgericht de juiste AI-tooling per functionele use-case.',
    ],
  },
  {
    id: 5,
    code: 'LU-5',
    title: 'Zelfstandig en zelfsturend werken',
    officialDescription: 'Je kunt een eigen leerroute vaststellen en uitvoeren waarbij je zelfstandig je leervragen stelt, relevante bronnen en tools selecteert, je eigen voortgang monitort en kritisch reflecteert op je leerproces en persoonlijke ontwikkeling in het AI-landschap.',
    status: 'Aangetoond',
    progressPercentage: 90,
    linkedEvidenceCount: 6,
    requiredMinPass: 6,
    criteria: [
      'Plant en realiseert circa 5 activiteiten per 2-wekelijkse sprint (Research, User, Learning Stories).',
      'Voert na elke sprint een grondige zelfevaluatie uit en verwerkt ontvangen feedback in reflecties.',
      'Levert minimaal 24 beoordeelde leeruitkomsten op voor het eindassessment (Op Niveau / Boven Niveau).',
    ],
  },
];

export const STORIES_DATA: StoryItem[] = [
  {
    id: 'story-1',
    sprintNumber: 1,
    type: 'Research Story',
    title: 'Vergelijking van Prompting Strategieën voor Gestructureerde Output',
    context: 'Bij het aansturen van taalmodellen voor webapps is onvoorspelbare tekst ongeschikt voor UI-parsing.',
    approachOrUserStory: 'Onderzoek uitgevoerd naar zero-shot vs few-shot system instructions en JSON mode met Gemini 3.1 Flash.',
    outcomeOrConclusion: 'Gedefinieerde schema’s in combinatie met strikte system instructions elimineren 99% van de formattingfouten.',
    tags: ['Prompt Engineering', 'Gemini API', 'JSON Schema'],
    date: 'Week 2',
    linkedOutcomeIds: [1, 2],
  },
  {
    id: 'story-2',
    sprintNumber: 2,
    type: 'User Story',
    title: 'Geavanceerd Zoeken & Stemmingsinzicht in Dagboek',
    context: 'Als dagboekgebruiker wil ik eerdere ervaringen eenvoudig kunnen terugvinden op trefwoord, datum en stemming.',
    approachOrUserStory: 'Als gebruiker wil ik zoeken in alle antwoorden en direct mijn stemmingstrends zien, zodat ik zelfreflectie kan verdiepen.',
    outcomeOrConclusion: 'Succesvol gerealiseerd met live tekstfilter, datumkiezer, interactief stemmingsoverzicht en favorieten-stermarkering.',
    tags: ['User Stories', 'Full-text Search', 'Mood Analytics', 'React State'],
    date: 'Week 3',
    linkedOutcomeIds: [2, 3],
  },
  {
    id: 'story-3',
    sprintNumber: 2,
    type: 'Learning Story',
    title: 'Server-Side Security & API Key Bescherming',
    context: 'Client-side API-keys blootstellen in de browser is een groot beveiligingsrisico in productie.',
    approachOrUserStory: 'Geleerd hoe Express in combinatie met Vite middleware als proxy fungeert zodat GEMINI_API_KEY strikt geheim blijft.',
    outcomeOrConclusion: 'Volledig werkende backend-route (/api/quote) opgezet met error-handling, fallback naar gemini-3.8-flash en JSON-response.',
    tags: ['Security', 'Express', 'Vite Middleware', 'TypeScript'],
    date: 'Week 4',
    linkedOutcomeIds: [1, 5],
  },
  {
    id: 'story-4',
    sprintNumber: 2,
    type: 'Research Story',
    title: 'Opslagmethoden Evaluatie: LocalStorage vs Cloud Database',
    context: 'Keuze voor de juiste persistentie voor een prototype met persoonlijke, privacygevoelige notities.',
    approachOrUserStory: 'Geanalyseerd op snelheid, privacy, persistentie bij browser refresh, apparaatonafhankelijkheid en verliesrisico’s.',
    outcomeOrConclusion: 'LocalStorage gekozen voor het prototype wegens nultarief en privacy-first lokale opslag; cloud synchronisatie gepland voor latere release.',
    tags: ['Architecture', 'Data Privacy', 'LocalStorage', 'Cloud SQL'],
    date: 'Week 4',
    linkedOutcomeIds: [2, 4],
  },
  {
    id: 'story-5',
    sprintNumber: 2,
    type: 'User Story',
    title: 'Data-Soevereiniteit: Volledige Excel-Export (.xlsx)',
    context: 'Gebruikers moeten ten alle tijden eigenaar blijven van hun eigen data en deze kunnen archiveren of analyseren.',
    approachOrUserStory: 'Als gebruiker wil ik met één klik alle notities downloaden als Excel (.xlsx) met datum, tijd, stemming en antwoorden.',
    outcomeOrConclusion: 'Geïmplementeerd met de sheetjs/xlsx library; gevalideerd dat alle kolommen en teksten exact overeenkomen.',
    tags: ['Excel Export', 'SheetJS', 'Data Portability', 'UX'],
    date: 'Week 4',
    linkedOutcomeIds: [3, 4],
  },
  {
    id: 'story-6',
    sprintNumber: 3,
    type: 'Learning Story',
    title: 'Vector Embeddings & Context Windows Begrijpen',
    context: 'Hoe kunnen we een AI antwoorden laten baseren op een eigen documentencollectie zonder finetuning?',
    approachOrUserStory: 'Bestuderen van cosine similarity, text-embedding modellen en chunking-strategieën voor RAG pipelines.',
    outcomeOrConclusion: 'Praktijkkennis opgedaan over optimale chunk-grootte (500 tokens met 50 overlap) voor nauwkeurige document retrieval.',
    tags: ['RAG', 'Vector Embeddings', 'Cosine Similarity', 'NLP'],
    date: 'Week 5',
    linkedOutcomeIds: [1, 2],
  },
];

export const PROJECTS_DATA: ProjectSolution[] = [
  {
    id: 'project-portfolio',
    sprintNumber: 1,
    title: 'Bouw je portfolio website met AI Studio 1',
    problemStatement: 'Studenten binnen de minor Futureproof met AI hebben één centrale plek nodig waar alle bewijzen, sprints, stories, prototypes en reflecties overzichtelijk verzameld worden om de 5 leeruitkomsten aan te tonen.',
    aiSolution: 'Een interactieve, persoonlijke en data-gedreven portfolio webapplicatie gebouwd met Google AI Studio en TypeScript/React. Bevat een centrale Bewijzenbank waar je links en opleveringen registreert, een persoonlijk wie-ben-ik profiel, story framework en directe koppeling naar live prototypes.',
    myRole: 'Ontwikkelaar & Student. Ontwerp van de informatiearchitectuur, interactieve bewijzenbank met sprint/LU filters, lokale datapersistentie en GitHub-synchronisatie.',
    demoUrl: 'https://ais-pre-kicwhcuqnw6anl342wcpjj-595862977345.europe-west1.run.app',
    githubUrl: 'https://github.com',
    tags: ['Google AI Studio', 'React 19', 'TypeScript', 'Tailwind CSS', 'Sprint 1 Oplevering'],
    highlights: [
      'Opdracht 1: centrale verzamelplek voor alle bewijzen voor sprintopleveringen en assessments',
      'Opdracht 2: persoonlijk profiel met foto’s en verhaal over wie ik ben en waar ik blij van word',
      'Direct bewerkbaar en lokaal opgeslagen via browser storage (bewijzen, stories, bio)',
      'Interactief overzicht van alle gemaakte stukken werk gekoppeld aan de 5 leeruitkomsten',
    ],
  },
  {
    id: 'project-1',
    sprintNumber: 2,
    title: 'AI Digitaal Dagboek & Zelfreflectie Assistent',
    problemStatement: 'Mensen willen dagelijks reflecteren, maar ervaren vaak een leeg-blad-syndroom of missen overzicht in hun emotionele ontwikkeling over tijd.',
    aiSolution: 'Een mensgerichte webapplicatie met een 4-vragen reflectiemethode, automatische stemmingstracking, Gemini-aangedreven dagelijkse inspiratiespreuken, PIN-beveiliging en Excel data-export.',
    myRole: 'Lead Full-Stack Developer & AI Integrator. Verantwoordelijk voor frontend architectuur, Express server proxy, prompting van Gemini, en dataportabiliteit via Excel.',
    demoUrl: 'https://ais-dev-kicwhcuqnw6anl342wcpjj-595862977345.europe-west1.run.app',
    githubUrl: 'https://github.com',
    tags: ['React 19', 'Tailwind CSS', 'Gemini 3.1 Flash', 'Express', 'SheetJS'],
    highlights: [
      'Veilige server-side Gemini API integratie via /api/quote met fouttolerantie',
      'Filter- en zoeksysteem met interactieve stemmingsteller en favorieten-stermodus',
      'Volledige export naar .xlsx bestand met één klik voor datasoevereiniteit',
      'PIN-code vergrendelingsscherm voor privacy in gedeelde omgevingen',
    ],
  },
  {
    id: 'project-2',
    sprintNumber: 1,
    title: 'Prompt Engineering Experimenteer-Suite',
    problemStatement: 'Verschillende LLM-modellen reageren wisselend op context, tone-of-voice instructies en constraints, wat vergelijkende tests vereist.',
    aiSolution: 'Een testomgeving waarin prompts systematisch getoetst worden op reproduceerbaarheid, tokenverbruik, reactiesnelheid en hallucinatiefrequenties.',
    myRole: 'Onderzoeker & Script Developer. Opstellen van gestandaardiseerde testprompts en kwantificeren van respons-kwaliteit.',
    githubUrl: 'https://github.com',
    tags: ['Gemini 3.8 Flash', 'Google AI Studio', 'Benchmarking', 'Prompt Design'],
    highlights: [
      'Gedocumenteerd overzicht van 12 geteste prompt archetypes',
      'Meting van latency en outputconsistentie over 50 testruns',
      'Opstellen van een "Best Practices" gids voor teamleden binnen de minor',
    ],
  },
  {
    id: 'project-3',
    sprintNumber: 3,
    title: 'Contextual RAG Kennis-Assistent (In Ontwikkeling)',
    problemStatement: 'Studenten verliezen veel tijd met het zoeken naar de juiste richtlijnen, assessmentcriteria en lesmaterialen binnen de minor.',
    aiSolution: 'Een intelligente assistent die lesstof, sprinthandleidingen en beoordelingsrubrieken doorzoekbaar maakt met feitelijke bronverwijzingen.',
    myRole: 'Architect van de data-ingestie pipeline en prompt orchestrator.',
    tags: ['Embeddings', 'Vector Search', 'RAG Pipeline', 'FastAPI / Node'],
    highlights: [
      'Automatische chunking en indexing van cursus-PDF’s',
      'Transparante bronvermelding bij elk gegenereerd antwoord',
      'Voorkomen van hallucinaties door strikte "answer only from context" parameters',
    ],
  },
];

export const AI_TOOLS_DATA: AIToolItem[] = [
  {
    id: 'tool-1',
    name: 'Google GenAI SDK & Gemini API',
    category: 'LLM & API',
    description: 'De officiële TypeScript SDK (@google/genai) voor het aanroepen van Gemini 3.1 Flash Lite en Gemini 3.8 Flash modellen.',
    howApplied: 'Gebruikt in Sprint 2 voor server-side generatie van gepersonaliseerde, contextuele reflectiespreuken en samenvattingen via Express backend.',
    usedInSprints: [1, 2, 3],
    promptOrCodeSnippet: `const response = await ai.models.generateContent({
  model: "gemini-3.1-flash-lite",
  contents: promptText,
  config: {
    systemInstruction: "Je bent een warme, bemoedigende assistent...",
    temperature: 0.9,
  },
});`,
  },
  {
    id: 'tool-2',
    name: 'Google AI Studio & Antigravity Agent',
    category: 'AI Coding & Agents',
    description: 'Cloudgebaseerde ontwikkelomgeving met autonome coderingsassistent die iteratieve refactoring, builds en dev-server orchestration uitvoert.',
    howApplied: 'Ingezet voor het bouwen van de volledige full-stack architectuur, unit tests, code synchronisatie met GitHub en visuele UI validatie.',
    usedInSprints: [1, 2, 3],
    promptOrCodeSnippet: `# Prompt voorbereiding:
"Voeg een knop 'Download als Excel' toe... zorg dat iedere notitie één rij krijgt met kolommen: datum, tijd, stemming..."`,
  },
  {
    id: 'tool-3',
    name: 'SheetJS / XLSX Data Portability Engine',
    category: 'Data & ML',
    description: 'High-performance spreadsheet generation library voor het omzetten van gestructureerde JSON-data naar binaire .xlsx bestanden.',
    howApplied: 'Geïntegreerd in het dagboek om gebruikers controle over hun data te geven conform AVG data-portabiliteitsrechten.',
    usedInSprints: [2],
    promptOrCodeSnippet: `const worksheet = XLSX.utils.json_to_sheet(rows);
const workbook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(workbook, worksheet, 'Dagboeknotities');
XLSX.writeFile(workbook, filename);`,
  },
  {
    id: 'tool-4',
    name: 'Tailwind CSS & Motion',
    category: 'Design & Prompts',
    description: 'Utility-first CSS framework en animatie-engine voor responsieve, toegankelijke en vloeiende gebruikerservaringen.',
    howApplied: 'Gebruikt voor een rustgevend, warm kleurenpalet (rood/beige/steen) en subtiele transitie-effecten bij navigatie en modale vensters.',
    usedInSprints: [1, 2],
    promptOrCodeSnippet: `<div className="bg-[#FAF7F2] text-stone-800 font-sans min-h-screen">`,
  },
];

export const FEEDBACK_REFLECTIONS_DATA: FeedbackReflectionItem[] = [
  {
    id: 'feedback-1',
    sprintNumber: 2,
    source: 'Docent',
    sourcePerson: 'Docent / Beoordelaar Minor Futureproof met AI',
    receivedFeedback: '“Sterke opzet van het dagboek met de 4 vragen en de Gemini-spreuk. Goed dat de API-key server-side beschermd is. Let erop dat je de data-opslag goed onderbouwt en gebruikers een exportmogelijkheid biedt voor data-soevereiniteit.”',
    reflectionWentWell: 'De scheiding tussen client en Express server werkte direct foutloos; ook het stemmingsoverzicht werd positief ontvangen als visualisatie.',
    reflectionToImprove: 'De afhankelijkheid van alleen localStorage brengt risico op dataverlies mee als de browsercache gewist wordt.',
    reflectionAction: 'Per direct een volwaardige Excel-export (.xlsx) toegevoegd met SheetJS en in de documentatie een migratieplan naar Firebase Firestore opgenomen.',
    evidenceItems: [
      {
        title: 'Excel Export Functionaliteit Test',
        type: 'Testresultaat',
        description: 'Geautomatiseerde node-test uitgevoerd waarbij 3 notities zijn geëxporteerd en gevalideerd met 100% correcte celwaarden.',
      },
      {
        title: 'Server-Side API Route Code (/api/quote)',
        type: 'Code',
        description: 'Volledige Express route met error handling en fallback naar gemini-3.8-flash.',
      },
    ],
  },
  {
    id: 'feedback-2',
    sprintNumber: 2,
    source: 'Peer / Student',
    sourcePerson: 'Medestudent Peer Review',
    receivedFeedback: '“De interface ziet er rustig en overzichtelijk uit. De ster-favorieten en het filteren op stemming werken erg fijn. Zou handig zijn als ik ook direct een datum kan kiezen in plaats van eindeloos scrollen.”',
    reflectionWentWell: 'De filters en zoekbalk zijn zeer intuïtief opgebouwd met directe feedback over het aantal gevonden notities.',
    reflectionToImprove: 'Datumselectie ontbrak nog in de eerste testversie, waardoor oude herinneringen lastig te vinden waren.',
    reflectionAction: 'HTML5 date-picker toegevoegd met een knop om alle actieve filters direct te resetten.',
    evidenceItems: [
      {
        title: 'Filter & Zoekbalk Component (EntryList.tsx)',
        type: 'Code',
        description: 'Gelijktijdige filtering op tekst, datum en specifieke gemoedstoestand.',
      },
      {
        title: 'GitHub Sync Bevestiging',
        type: 'Document',
        description: 'Codebase gekoppeld en gesynchroniseerd met GitHub repository via Google AI Studio.',
      },
    ],
  },
  {
    id: 'feedback-3',
    sprintNumber: 1,
    source: 'Expert / Opdrachtgever',
    sourcePerson: 'Gastspreker AI Interaction Design',
    receivedFeedback: '“Bij generatieve AI is de framing van de AI cruciaal: laat het model niet doen alsof het menselijk is, maar geef het een duidelijke rol als reflectieve assistent.”',
    reflectionWentWell: 'In de system prompt is direct gekozen voor de rol van een reflectieve, warme assistent in plaats van een algemene chatbot.',
    reflectionToImprove: 'Soms duurde het ophalen van een spreuk net iets te lang zonder laadstatus.',
    reflectionAction: 'Duidelijke loading spinner en fallback spreuk geïmplementeerd zodat de interface nooit blokkeert.',
    evidenceItems: [
      {
        title: 'Prompt Architecture Documentatie',
        type: 'Document',
        description: 'System instructions en temperature instellingen vastgelegd in server.ts.',
      },
    ],
  },
];
