import {
  StudentProfile,
  SprintData,
  LearningOutcome,
  StoryItem,
  ProjectSolution,
  AIToolItem,
  FeedbackReflectionItem,
  EvidenceLink,
  WorkItem,
} from './portfolioTypes';

/*
 * Inhoud van het portfolio.
 * Alles wat hier staat komt uit mijn logboek (Minor Futureproof met AI).
 * Lege velden ('') worden op de site als "nog invullen" getoond.
 */

export const STUDENT_PROFILE: StudentProfile = {
  name: 'Justin Man',
  title: 'Student Minor Futureproof met AI',
  institution: 'Hogeschool Utrecht',
  program: 'Commerciële Economie (HAN)',
  minor: 'Minor Futureproof met AI',
  academicYear: '2026 - 2027',
  bio: 'Welkom op mijn portfolio voor de minor Futureproof met AI. Als student Commerciële Economie onderzoek ik hoe AI het beroep van accountmanager verandert en welke AI-vaardigheden ik daarvoor nodig heb. Per sprint laat ik zien wat ik heb onderzocht, gemaakt en geleerd, met het bewijs erbij.',
  email: 'justinman@outlook.com',
  githubUrl: '',
  linkedinUrl: '',
  location: '',
  avatarUrl: '',
  personalStory: {
    whoAmI: '',
    passionsAndJoy: '',
    whyThisMinor: '',
    photoUrl: '',
    funFacts: [],
  },
  learningGoals: [],
};

/** Achtergrond uit mijn cv, getoond op de pagina "Over mij". */
export const CV_BACKGROUND = {
  intro: 'Ik ben derdejaars student Commerciële Economie met een brede interesse in commerciële en dienstverlenende functies. Ik werk graag met mensen, ben communicatief vaardig en pak nieuwe taken snel op. In mijn werkervaring heb ik geleerd om klantgericht te denken, verantwoordelijkheid te nemen en effectief samen te werken.',
  education: [
    {
      title: 'Minor Artificial Intelligence & Digital Innovation (Futureproof met AI)',
      place: 'Hogeschool Utrecht',
      period: 'september 2026 – heden',
      description: 'Multidisciplinaire minor gericht op het toepassen van AI binnen de toekomstige beroepspraktijk. Ik onderzoek de impact van AI op het commerciële werkveld en ontwikkel praktische AI-oplossingen.',
    },
    {
      title: 'Commerciële Economie (hbo)',
      place: 'Hogeschool van Arnhem en Nijmegen',
      period: 'september 2024 – heden',
      description: 'Brede commerciële opleiding gericht op marketing, sales, ondernemerschap en klantgericht werken, met ervaring in marktonderzoek, klant- en marktanalyses en commerciële adviezen.',
    },
    {
      title: 'HAVO, profiel Economie & Maatschappij',
      place: 'Christelijk Lyceum Veenendaal',
      period: 'september 2017 – februari 2022',
      description: '',
    },
  ],
  experience: [
    {
      title: 'Receptiemedewerker',
      place: 'Feel Fit Center Rhenen',
      period: 'oktober 2023 – februari 2026',
      description: 'Eerste aanspreekpunt voor leden en bezoekers van de sportschool en het zwembad: klanten ontvangen en helpen met vragen over abonnementen en diensten, telefoon en e-mail, inschrijvingen en betalingen verwerken en klachten klantgericht oplossen.',
    },
    {
      title: 'Retail support medewerker',
      place: 'DPD Veenendaal',
      period: 'mei 2023 – juli 2023',
      description: 'Ondersteuning van het logistieke proces in het distributiecentrum: contact met pakketpunten en afdelingen, zendingen registreren en controleren, afwijkingen oplossen en klantvragen afhandelen.',
    },
    {
      title: 'Junior vloerspecialist',
      place: 'Progenta bv, Elst',
      period: 'juni 2022 – september 2022',
      description: 'Voorbereiden en afwerken van vloeren, op locatie en in teamverband.',
    },
  ],
  skills: [
    'Verkoopgesprekken',
    'Klantenservice',
    'Klantenondersteuning',
    'Communicatieve vaardigheden',
    'Actief luisteren',
    'Analytisch vermogen',
    'Samenwerken',
    'Aanpassingsvermogen',
    'Betrouwbaar',
    'Sociaal',
  ],
  languages: ['Nederlands – vloeiend', 'Engels – vloeiend'],
  other: ['Rijbewijs B'],
};

export const INITIAL_WORK_ITEMS: WorkItem[] = [
  {
    id: 's1-verslag-lu1',
    title: 'Verslag LU1 – AI-impact op het beroep Accountmanager',
    sprintNumber: 1,
    type: 'Word-bestand',
    whatMade: 'Verslag over de vraag: welke invloed heeft AI op het werk van een accountmanager en welke vaardigheden heeft een accountmanager nodig om AI effectief te gebruiken? Met een beschrijving van het beroep, wat AI kan ondersteunen en wat niet, een vergelijking van drie AI-toepassingen (leadgeneratie en -kwalificatie, voorbereiding van klantgesprekken, gespreksverwerking met CRM-automatisering), vijf concrete AI-vaardigheden, mijn praktische ervaring in sprint 1 en een samenvatting voor de Show & Grow.',
    howMadeOrTech: 'Bronnenonderzoek (o.a. Indeed, McKinsey, Microsoft en wetenschappelijke artikelen)',
    learningOutcomeCodes: ['LU-1', 'LU-4', 'LU-5'],
    storyIds: ['s1-rs1', 's1-ls2'],
    url: '/bewijs/sprint-1/Verslag-LU1-AI-impact-accountmanager-Justin-Man.docx',
    status: 'Opgeleverd',
    dateAdded: '2026-09-16',
  },
  {
    id: 's1-portfolio',
    title: 'Portfoliowebsite + online dagboek (Google AI Studio)',
    sprintNumber: 1,
    type: 'Werkend Prototype',
    whatMade: 'Mijn eigen portfoliowebsite met online dagboek, ontworpen en gebouwd met Google AI Studio, waarin ik mijn werk, leeruitkomsten en bewijzen kan presenteren.',
    howMadeOrTech: 'Google AI Studio, Visual Studio Code',
    learningOutcomeCodes: ['LU-2', 'LU-4'],
    storyIds: ['s1-us1'],
    url: '',
    status: 'Opgeleverd',
    dateAdded: '2026-09-16',
  },
  {
    id: 's1-logboek',
    title: 'Integraal Sprint Logboek',
    sprintNumber: 1,
    type: 'Excel-bestand',
    whatMade: 'Mijn logboek met per sprint de planning (stories), ontvangen feedback, zelfevaluatie per leeruitkomst en reflectie.',
    howMadeOrTech: 'Excel',
    learningOutcomeCodes: ['LU-5'],
    storyIds: ['s1-rs1', 's1-ls1', 's1-us1', 's1-ls2'],
    url: '/bewijs/sprint-1/Logboek-Minor-Futureproof-met-AI-Justin-Man.xlsx',
    status: 'Opgeleverd',
    dateAdded: '2026-09-16',
  },
  {
    id: 's1-vscode',
    title: 'Screenshots van Visual Studio Code',
    sprintNumber: 1,
    type: 'Afbeelding / screenshot',
    whatMade: 'Screenshots die laten zien dat ik mijn project lokaal heb geopend en gestart in Visual Studio Code.',
    howMadeOrTech: 'Visual Studio Code',
    learningOutcomeCodes: ['LU-4', 'LU-5'],
    storyIds: ['s1-ls2'],
    url: '',
    status: 'Opgeleverd',
    dateAdded: '2026-09-16',
  },
  {
    id: 's1-prompts',
    title: 'Gebruikte prompts en AI-tools',
    sprintNumber: 1,
    type: 'Prompt Systeem',
    whatMade: 'Overzicht van de prompts die ik heb gebruikt en de AI-tools waarmee ik heb gewerkt.',
    howMadeOrTech: 'ChatGPT, Gemini, Perplexity, Google AI Studio',
    learningOutcomeCodes: ['LU-4'],
    storyIds: [],
    url: '',
    status: 'Opgeleverd',
    dateAdded: '2026-09-16',
  },
];

export const INITIAL_EVIDENCE_LINKS: EvidenceLink[] = INITIAL_WORK_ITEMS;

export const SPRINTS_DATA: SprintData[] = [
  {
    number: 1,
    title: 'Sprint 1',
    theme: 'AI-impact op accountmanagement & mijn portfolio',
    period: 'Week 1 - 2',
    summary: 'Onderzoek de impact van AI op accountmanagement, leer AI gebruiken voor klantonderzoek en bouw je persoonlijke bewijsportfolio.',
    focusAreas: ['AI-impact accountmanager', 'Klantonderzoek', 'Portfoliowebsite', 'Visual Studio Code'],
    status: 'Afgerond',
    activities: [
      'Zelfstandig mijn werkzaamheden voor deze sprint gepland, uitgevoerd en bijgehouden.',
      'Zelf mijn stories (RS, US en LS) opgesteld en verwerkt in mijn integraal sprintlogboek.',
      'Onderzoek uitgevoerd naar de impact van AI op accountmanagement: waar AI kan ondersteunen, wat de menselijke kant van het beroep blijft en welke AI-vaardigheden belangrijk worden.',
      'Met Google AI Studio een eigen portfoliowebsite + online dagboek ontworpen en gebouwd.',
      'Verschillende tools leren gebruiken en koppelen: Google AI Studio, GitHub en Visual Studio Code.',
      'ChatGPT, Gemini en Perplexity gebruikt bij het maken en verbeteren van prompts, het opzoeken van informatie en het krijgen van tips.',
      'Wanneer ik tijdens het bouwen vastliep, AI-tools gebruikt om zelf oplossingen en uitleg te vinden.',
    ],
    feedback: [
      {
        date: '10-9-2026',
        from: '',
        feedback: '',
        action: 'Nog geen feedback mogen ontvangen: deze dag was ik ziek.',
      },
    ],
    selfEvaluation: [
      {
        code: 'LU-1',
        level: 'V',
        argument: 'Ik heb onderzocht wat de impact van AI is op mijn toekomstige beroep als accountmanager. Ik heb onderzocht waar AI kan ondersteunen, wat de menselijke kant van het beroep blijft en welke AI-vaardigheden belangrijk worden voor accountmanagers. Bewijs: Verslag Leeruitkomst 1 – AI-impact op het beroep Accountmanager.',
      },
      {
        code: 'LU-2',
        level: 'V',
        argument: 'Ik heb met Google AI Studio een eigen portfoliowebsite + online dagboek ontworpen en gebouwd waarin ik mijn werk, leeruitkomsten en bewijzen kan presenteren. Hiermee heb ik een werkend digitaal product gerealiseerd met behulp van AI. Bewijs: mijn werkende portfoliowebsite, opgenomen als bewijs bij Sprint 1.',
      },
      {
        code: 'LU-3',
        level: '-',
        argument: '',
      },
      {
        code: 'LU-4',
        level: 'V',
        argument: 'Ik heb verschillende AI- en digitale tools toegepast. Met Google AI Studio heb ik mijn portfolio gebouwd, via GitHub heb ik de code opgeslagen en beheerd en in Visual Studio Code heb ik mijn project lokaal geopend en verder bewerkt. Daarnaast heb ik ChatGPT, Gemini en Perplexity gebruikt als ondersteuning bij het maken en verbeteren van prompts, het opzoeken van informatie en het krijgen van tips tijdens het proces. Bewijs: mijn portfoliowebsite, screenshots van Visual Studio Code en mijn gebruikte prompts en AI-tools, toegevoegd bij Sprint 1.',
      },
      {
        code: 'LU-5',
        level: 'V',
        argument: 'Ik heb deze sprint zelfstandig mijn werkzaamheden gepland, uitgevoerd en bijgehouden. Ik heb zelf mijn stories opgesteld en verwerkt in mijn integraal sprintlogboek. Daarnaast heb ik zelfstandig mijn portfoliowebsite gebouwd, verschillende tools leren gebruiken en koppelen en mijn onderzoek naar de impact van AI op accountmanagement uitgevoerd. Wanneer ik tijdens het bouwen vastliep, heb ik AI-tools gebruikt om zelf oplossingen en uitleg te vinden. Bewijs: Integraal Sprint Logboek, onderzoeksverslag AI-impact op accountmanagement, portfoliowebsite en gebruikte prompts.',
      },
    ],
    reflection: {
      date: '16-9-2026',
      learned: 'Ik heb geleerd hoe ik met AI een website kan bouwen en hoe Google AI Studio, GitHub en Visual Studio Code samenwerken. Ook heb ik meer geleerd over de invloed van AI op mijn toekomstige beroep als accountmanager.',
      keep: 'Ik wil blijven leren door zelf dingen uit te proberen en direct toe te passen. Vooral het werken met verschillende AI-tools en vervolgens kijken welke tool het beste werkt voor een bepaalde taak wil ik behouden. Ook wil ik mijn werk per sprint blijven vastleggen, zodat mijn ontwikkeling en bewijs duidelijk terug te zien zijn.',
      change: 'Tijdens het feedbackmoment was ik ziek, waardoor ik geen feedback heb kunnen ophalen. In de volgende sprint wil ik daarom eerder feedback vragen aan medestudenten of mijn coach, zodat ik niet afhankelijk ben van één feedbackmoment en mijn werk tussentijds kan verbeteren.',
    },
  },
  {
    number: 2,
    title: 'Sprint 2',
    theme: '',
    period: '',
    summary: '',
    focusAreas: [],
    status: 'In uitvoering',
  },
  {
    number: 3,
    title: 'Sprint 3',
    theme: '',
    period: '',
    summary: '',
    focusAreas: [],
    status: 'Gepland',
  },
  {
    number: 4,
    title: 'Sprint 4',
    theme: '',
    period: '',
    summary: '',
    focusAreas: [],
    status: 'Gepland',
  },
  {
    number: 5,
    title: 'Sprint 5',
    theme: '',
    period: '',
    summary: '',
    focusAreas: [],
    status: 'Gepland',
  },
  {
    number: 6,
    title: 'Sprint 6',
    theme: '',
    period: '',
    summary: '',
    focusAreas: [],
    status: 'Gepland',
  },
  {
    number: 7,
    title: 'Sprint 7',
    theme: '',
    period: '',
    summary: '',
    focusAreas: [],
    status: 'Gepland',
  },
  {
    number: 8,
    title: 'Sprint 8',
    theme: '',
    period: '',
    summary: '',
    focusAreas: [],
    status: 'Gepland',
  },
];

export const LEARNING_OUTCOMES: LearningOutcome[] = [
  {
    id: 1,
    code: 'LU-1',
    title: 'AI-impact op de toekomstige beroepspraktijk analyseren en evalueren',
    officialDescription: 'Je kunt zelfstandig onderzoek doen naar de impact van AI in jouw toekomstig beroep en vaststellen welke nieuwe AI en digitale vaardigheden daarvoor nodig zijn.',
    status: 'In ontwikkeling',
    progressPercentage: 0,
    linkedEvidenceCount: 0,
    requiredMinPass: 2,
    criteria: [
      'Onderzoekt hoe AI werkprocessen, rollen en competenties in het vakgebied transformeert.',
      'Formuleert gerichte leervragen over nieuwe benodigde AI- en digitale vaardigheden.',
      'Onderbouwt analyses met actuele bronnen, expertinterviews of praktijkcases.',
    ],
  },
  {
    id: 2,
    code: 'LU-2',
    title: 'Praktijkgerichte AI oplossing ontwerpen, realiseren en presenteren',
    officialDescription: 'Je kunt zelfstandig een AI oplossing ontwerpen, realiseren en presenteren die een specifieke beroepspraktijk radicaal transformeert (verandert).',
    status: 'In ontwikkeling',
    progressPercentage: 0,
    linkedEvidenceCount: 0,
    requiredMinPass: 4,
    criteria: [
      'Ontwerpt en bouwt werkende AI proof-of-concepts (apps, prototypes, vibe-coding applicaties).',
      'Definieert duidelijke acceptatie- en kwaliteitscriteria voor oplevering in sprints.',
      'Presenteert het gerealiseerde product overtuigend tijdens Show & Tell sessies.',
    ],
  },
  {
    id: 3,
    code: 'LU-3',
    title: 'Ethiek en verantwoordelijk AI-gebruik beoordelen',
    officialDescription: 'Je kunt zelfstandig de ethische vraagstukken en uitdagingen van AI in je vakgebied identificeren en aanbevelingen formuleren voor verantwoord AI-gebruik, rekening houdend met privacy, bias en transparantie.',
    status: 'In ontwikkeling',
    progressPercentage: 0,
    linkedEvidenceCount: 0,
    requiredMinPass: 2,
    criteria: [
      'Identificeert risico’s rondom privacy, datasoevereiniteit, hallucinaties en bias.',
      'Formuleert concrete aanbevelingen voor verantwoord en transparant AI-gebruik.',
      'Implementeert maatregelen (bijv. lokale gegevensverwerking, veilige API-sleutels, gebruikerscontrole).',
    ],
  },
  {
    id: 4,
    code: 'LU-4',
    title: 'AI Tools en technieken gebruiken',
    officialDescription: 'Je kunt zelfstandig verschillende AI-tools en platforms toepassen (zoals AI machine learning technieken, chatbots, agents, prompts, etc) en deze gebruiken om specifieke taken binnen je vakgebied op te lossen.',
    status: 'In ontwikkeling',
    progressPercentage: 0,
    linkedEvidenceCount: 0,
    requiredMinPass: 4,
    criteria: [
      'Past geavanceerde promptingtechnieken, LLM-APIs en Vibe-coding toe.',
      'Bouwt en orchestreert AI-agents en geautomatiseerde workflows (zoals n8n, Make, scripts).',
      'Selecteert doelgericht de juiste AI-tooling per functionele use-case.',
    ],
  },
  {
    id: 5,
    code: 'LU-5',
    title: 'Zelfstandig en zelfsturend werken',
    officialDescription: 'Je kunt een eigen leerroute vaststellen en uitvoeren waarbij je zelfstandig je leervragen stelt, relevante bronnen en tools selecteert, je eigen voortgang monitort en kritisch reflecteert op je leerproces en persoonlijke ontwikkeling in het AI-landschap.',
    status: 'In ontwikkeling',
    progressPercentage: 0,
    linkedEvidenceCount: 0,
    requiredMinPass: 6,
    criteria: [
      'Plant en realiseert circa 5 activiteiten per 2-wekelijkse sprint (Research, User, Learning Stories).',
      'Voert na elke sprint een grondige zelfevaluatie uit en verwerkt ontvangen feedback in reflecties.',
      'Levert minimaal 24 beoordeelde leeruitkomsten op voor het eindassessment (Op Niveau / Boven Niveau).',
    ],
  },
];

export const STORIES_DATA: StoryItem[] = [
  {
    id: 's1-rs1',
    sprintNumber: 1,
    type: 'Research Story',
    title: 'AI-impact op het beroep accountmanager',
    description: 'Als student Commerciële Economie wil ik onderzoeken welke impact AI heeft op het beroep accountmanager, zodat ik weet welke werkzaamheden veranderen en welke AI-vaardigheden ik moet ontwikkelen.',
    context: 'Als student Commerciële Economie bereid ik me voor op het beroep accountmanager. Centrale vraag: welke invloed heeft AI op het werk van een accountmanager en welke vaardigheden heeft een accountmanager nodig om AI effectief te kunnen gebruiken?',
    approachOrUserStory: 'Bronnenonderzoek naar het beroep en de inzet van AI (o.a. Indeed, McKinsey, Microsoft en wetenschappelijke artikelen over vertrouwen in verkopers). Drie AI-toepassingen vergeleken op tijdwinst, commerciële waarde, gebruiksgemak, betrouwbaarheid en risico’s.',
    outcomeOrConclusion: 'AI vervangt de accountmanager niet, maar ondersteunt vooral bij voorbereiding, analyse, communicatie en administratie. De menselijke kant blijft belangrijk: klanten aanvoelen, vertrouwen opbouwen, overtuigen en onderhandelen. Vijf AI-vaardigheden: goed prompten, AI-output controleren, AI gebruiken voor klantonderzoek, AI gebruiken binnen CRM en verkoopprocessen, en verantwoord omgaan met AI en klantgegevens. Uitgewerkt in het verslag “Leeruitkomst 1 – AI-impact op het beroep Accountmanager”.',
    tags: ['Accountmanagement', 'AI-impact', 'Onderzoek'],
    date: 'Sprint 1',
    linkedOutcomeIds: [1],
    acceptanceCriteria: [
      'Het onderzoek beschrijft de huidige werkzaamheden van een accountmanager.',
      'Er wordt onderscheid gemaakt tussen taken die AI overneemt, ondersteunt en niet kan vervangen.',
      'Minimaal drie AI-toepassingen binnen accountmanagement worden onderzocht en vergeleken: leadgeneratie en leadkwalificatie, voorbereiding van klantgesprekken en gespreksverwerking met CRM-automatisering.',
    ],
    qualityCriteria: [
      'Beweringen worden onderbouwd met bronnen, voorbeelden of resultaten uit de eigen casus.',
      'Vaste vergelijking: de drie toepassingen worden beoordeeld op tijdwinst, commerciële waarde, gebruiksgemak, betrouwbaarheid en risico’s.',
      'Beroepsrelevantie: de conclusies worden vertaald naar minimaal vijf concrete AI-vaardigheden voor accountmanagers.',
    ],
  },
  {
    id: 's1-ls1',
    sprintNumber: 1,
    type: 'Learning Story',
    title: 'AI gebruiken voor klantonderzoek',
    description: 'Als toekomstige accountmanager wil ik leren hoe ik AI gebruik voor klantonderzoek, zodat ik betrouwbare klantinformatie kan verzamelen.',
    context: '',
    approachOrUserStory: '',
    outcomeOrConclusion: '',
    tags: ['Klantonderzoek', 'AI-tools', 'Prompts'],
    date: 'Sprint 1',
    linkedOutcomeIds: [4],
    acceptanceCriteria: [
      'Ik heb minimaal twee AI-tools uitgeprobeerd.',
      'Ik heb met AI een klantonderzoek uitgevoerd.',
      'Ik heb mijn prompts en resultaten opgeslagen.',
    ],
    qualityCriteria: [
      'De gevonden informatie komt uit betrouwbare bronnen.',
      'Belangrijke informatie is gecontroleerd.',
      'Ik kan uitleggen welke tool en prompt het beste werkte.',
    ],
  },
  {
    id: 's1-us1',
    sprintNumber: 1,
    type: 'User Story',
    title: 'Portfoliowebsite bouwen met AI',
    description: 'Als student wil ik met AI een eigen portfoliowebsite maken, zodat ik mijn werk en bewijzen van de minor op één plek kan verzamelen en presenteren.',
    context: '',
    approachOrUserStory: '',
    outcomeOrConclusion: 'Met Google AI Studio heb ik een eigen portfoliowebsite + online dagboek ontworpen en gebouwd waarin ik mijn werk, leeruitkomsten en bewijzen kan presenteren.',
    tags: ['Google AI Studio', 'Portfolio'],
    date: 'Sprint 1',
    linkedOutcomeIds: [2, 4],
    acceptanceCriteria: [
      'Er is een werkende portfoliowebsite gemaakt met Google AI Studio.',
      'De website bevat informatie over mijzelf en ruimte voor mijn leeruitkomsten en bewijzen.',
      'De website kan worden aangepast en aangevuld met nieuwe bewijzen en leeruitkomsten.',
    ],
    qualityCriteria: [
      'De website heeft een duidelijke en overzichtelijke indeling.',
      'De belangrijkste onderdelen zijn makkelijk terug te vinden.',
      'De vormgeving en inhoud zijn consistent, zodat de verschillende onderdelen van het portfolio één geheel vormen.',
    ],
  },
  {
    id: 's1-ls2',
    sprintNumber: 1,
    type: 'Learning Story',
    title: 'Mijn AI-website lokaal beheren en aanpassen',
    description: 'Als student wil ik leren hoe ik mijn AI-gebouwde website via GitHub in Visual Studio Code kan gebruiken, zodat ik mijn code kan bewaren, bekijken en verder kan aanpassen.',
    context: '',
    approachOrUserStory: '',
    outcomeOrConclusion: 'Ik heb geleerd hoe Google AI Studio, GitHub en Visual Studio Code samenwerken en heb mijn project lokaal geopend en verder bewerkt in Visual Studio Code.',
    tags: ['Visual Studio Code', 'Google AI Studio'],
    date: 'Sprint 1',
    linkedOutcomeIds: [4, 5],
    acceptanceCriteria: [
      'Mijn portfolio uit Google AI Studio is gekoppeld aan een GitHub-repository.',
      'Ik heb het GitHub-project geopend in Visual Studio Code.',
      'Ik kan mijn website lokaal starten en de bestanden/code bekijken.',
    ],
    qualityCriteria: [
      'De actuele versie van mijn project staat correct opgeslagen in GitHub.',
      'Ik kan uitleggen waarvoor Google AI Studio, GitHub en Visual Studio Code afzonderlijk worden gebruikt.',
      'Ik kan aantonen dat het project vanuit Visual Studio Code lokaal werkt.',
    ],
  },
];

export const PROJECTS_DATA: ProjectSolution[] = [
  {
    id: 'project-portfolio',
    sprintNumber: 1,
    title: 'Portfoliowebsite + online dagboek',
    problemStatement: 'Voor de minor Futureproof met AI wil ik mijn werk en bewijzen op één plek verzamelen en presenteren.',
    aiSolution: 'Met Google AI Studio heb ik een eigen portfoliowebsite + online dagboek ontworpen en gebouwd waarin ik mijn werk, leeruitkomsten en bewijzen kan presenteren. Het project heb ik lokaal geopend en verder bewerkt in Visual Studio Code.',
    myRole: 'Zelfstandig ontworpen, gebouwd en bijgehouden.',
    tags: ['Google AI Studio', 'Visual Studio Code', 'Sprint 1'],
    highlights: [
      'Werkende portfoliowebsite gemaakt met Google AI Studio',
      'Informatie over mijzelf en ruimte voor leeruitkomsten en bewijzen',
      'Aan te passen en aan te vullen met nieuwe bewijzen en leeruitkomsten',
    ],
  },
];

export const AI_TOOLS_DATA: AIToolItem[] = [
  {
    id: 'tool-ai-studio',
    name: 'Google AI Studio',
    category: 'AI Coding & Agents',
    description: 'Omgeving van Google waarmee je met AI apps en websites kunt bouwen.',
    howApplied: 'Mijn portfoliowebsite + online dagboek ontworpen en gebouwd.',
    usedInSprints: [1],
  },
  {
    id: 'tool-chatgpt',
    name: 'ChatGPT',
    category: 'LLM & API',
    description: 'AI-chatassistent van OpenAI.',
    howApplied: 'Ondersteuning bij het maken en verbeteren van prompts, het opzoeken van informatie en het krijgen van tips tijdens het proces.',
    usedInSprints: [1],
  },
  {
    id: 'tool-gemini',
    name: 'Gemini',
    category: 'LLM & API',
    description: 'AI-chatassistent van Google.',
    howApplied: 'Ondersteuning bij het maken en verbeteren van prompts, het opzoeken van informatie en het krijgen van tips tijdens het proces.',
    usedInSprints: [1],
  },
  {
    id: 'tool-perplexity',
    name: 'Perplexity',
    category: 'LLM & API',
    description: 'AI-zoekmachine die antwoorden geeft met bronnen.',
    howApplied: 'Informatie opzoeken en ondersteuning bij het verbeteren van prompts.',
    usedInSprints: [1],
  },
  {
    id: 'tool-vscode',
    name: 'Visual Studio Code',
    category: 'Ontwikkeltools',
    description: 'Code-editor om projecten lokaal te openen en te bewerken.',
    howApplied: 'Mijn portfolioproject lokaal geopend, gestart en verder bewerkt.',
    usedInSprints: [1],
  },
];

export const FEEDBACK_REFLECTIONS_DATA: FeedbackReflectionItem[] = [];
